# Action description and parameters
name: 'SOFA Setup Action'
description: 'Setup everything needed to build a SOFA plugin'
inputs:
  sofa_install_path:
    description: 'Sofa install directory'
    required: true
  scenes_path:
    description: 'Scene test directory'
    required: true
  regression_file_path:
    description: 'Regression test configuration file directory'
    required: true
outputs:
  scene_test_results:
    description: "Log file containing scene tests results"
    value: ${{ steps.set-env-vars.outputs.scene_test_results_path }}
  regression_test_results:
    description: "Log file containing regression tests results"
    value: ${{ steps.set-env-vars.outputs.regression_test_results_path }}

# Action code
runs:
  using: "composite"
  steps:
    - name: Fetch CI repository
      shell: bash
      run: |  
     

    - name: Run scenes tests
      shell: bash
      run: |
        source scene-tests.sh
        initialize-scene-tests $output_dir $scenes_path
        test-all-scenes "$output_dir/all-tested-scenes.txt" $output_dir
        print-summary $output_dir
        //TODO check si il y a eu des erreurs et dans ce cas return 1 sinon 0




    - name: Fetch and install Regression_test
      shell: bash
      run: |
        if [[ "$RUNNER_OS" != "macOS" ]]; then
          # Get regression from github releases
          mkdir -p "${{ runner.temp }}/regression_tmp/install"
          curl --output "${{ runner.temp }}/regression_tmp/${RUNNER_OS}.zip" -L https://github.com/sofa-framework/regression/releases/download/release-master/Regression_test_master_for-SOFA-${{ steps.sofa.outputs.sofa_version }}_${RUNNER_OS}.zip
          unzip -qq "${{ runner.temp }}/regression_tmp/${RUNNER_OS}.zip" -d "${{ runner.temp }}/regression_tmp/install"
          # Install it in the SOFA bin directory
          $SUDO mv "${{ runner.temp }}"/regression_tmp/install/Regression_*/bin/* "${SOFA_ROOT}/bin"
          chmod +x ${SOFA_ROOT}/bin/Regression_test${{ steps.sofa.outputs.exe }}
          # Setup mandatory env vars
          export REGRESSION_SCENES_DIR="${WORKSPACE_SRC_PATH}/examples"
          export REGRESSION_REFERENCES_DIR="${WORKSPACE_SRC_PATH}/regression/references"
          # Run regression test bench
          ${SOFA_ROOT}/bin/Regression_test${{ steps.sofa.outputs.exe }}
        else
          echo "Regression tests are not supported on the CI for macOS yet (TODO)"
        fi

    - name: Run regression tests
      shell: bash
      run: |