# Action description and parameters
name: 'SOFA Setup Action'
description: 'Setup everything needed to build a SOFA plugin'
inputs:
  sofa_root:
    description: 'SOFA install directory to get Regression binary, set SOFA_ROOT variable and append the PYTHONPATH env variable'
    required: true
  sofa_version:
    description: 'Version of SOFA used. Needed to know which binary verison of Regression to use (either master or a release e.g. v24.12)'
    required: true
  src_dir:
    description: 'Directory of the sources of the plugin to be tested (regression file will be looked for in example folder)'
    required: true
  build_dir:
    description: 'Build directory of the plugin. Used to include bindings if some are compiled by this plugin'
    required: true
  output_dir:
    description: 'Directory where to dump logs and results of tests. Will be created if it does not exist'
    required: true
  python_exe:
    description: 'path to python executable'
    required: true
  run_unit_tests:
    description: 'If true, will run the unit tests found in the build_dir/bin'
    required: false
    default: 'true'
  run_scene_tests:
    description: 'If true, will run all the scene found under src_dir/examples'
    required: false
    default: 'true'
  run_regression_tests:
    description: 'If true, will run the regression tests found in the src_dir/examples'
    required: false
    default: 'true'
  nb_parallel_threads:
    description: 'Tests will be run in parallel, this is the maximum number of thread allowed'
    required: false
    default: '1'
  ci_dir:
    description: 'Directory of the clone of the ci repository. If none is given, the plugin will be fetched by this action'
    required: false
  regression_dir:
    description: 'Directory of the clone of the Regression repository. If none is given, the plugin will be fetched by this action'
    required: false
  publish_logs:
    description: 'Boolean stating if the logs should be directly published by the action'
    required: false
    default: 'true'
outputs:
  unit_test_results:
    description: "Log file containing scene tests results"
    value: ${{ steps.set-env-vars.outputs.scene_test_results_path }}
  unit_test_results_path:
    description: "Log file containing scene tests results"
    value: ${{ steps.set-env-vars.outputs.scene_test_results_path }}
  scene_test_results:
    description: "Log file containing scene tests results"
    value: ${{ steps.set-env-vars.outputs.scene_test_results_path }}
  scene_test_results_path:
    description: "Log file containing scene tests results"
    value: ${{ steps.set-env-vars.outputs.scene_test_results_path }}
  regression_test_results:
    description: "Log file containing regression tests results"
    value: ${{ steps.set-env-vars.outputs.regression_test_results_path }}
  regression_test_results_path:
    description: "Log file containing regression tests results"
    value: ${{ steps.set-env-vars.outputs.regression_test_results_path }}

runs:
  using: "composite"
  steps:

    - name: Clone missing CI plugin 
      uses: actions/checkout@v4
      if: inputs.ci_dir == ''
      with:
        repository: 'bakpaul/ci'
        ref: 'jenkins_gha_migration'
        path: ci

    - name: Clone missing Regression plugin 
      uses: actions/checkout@v4
      if: inputs.regression_dir == ''
      with:
        repository: 'sofa-framework/Regression'
        ref: 'master'
        path: Regression

    - name: Setup environement for tests
      shell: bash
      run: |

        if [[ ! -d "${{ inputs.output_dir }}" ]]; then
            mkdir -p "${{ inputs.output_dir }}"
        fi


        WORKSPACE_DIR=$(cd ${{ github.workspace }} && pwd)
        echo "WORKSPACE_DIR=$WORKSPACE_DIR" >> $GITHUB_ENV

        CI_DIR=${{ inputs.ci_dir }}
        if [[ -z "$CI_DIR" ]]; then
            CI_DIR="$WORKSPACE_DIR/ci"
        fi
        echo "CI_DIR=$CI_DIR" >> $GITHUB_ENV
        
        REGRESSION_DIR=${{ inputs.regression_dir }}
        if [[ -z "$REGRESSION_DIR" ]]; then
            REGRESSION_DIR="$WORKSPACE_DIR/Regression"
        fi
        echo "REGRESSION_DIR=$REGRESSION_DIR" >> $GITHUB_ENV


        ##Install Regression release
        mkdir -p "${{ runner.temp }}/regression_tmp"
        curl --output "${{ runner.temp }}/regression_tmp/${RUNNER_OS}.zip" -L https://github.com/sofa-framework/regression/releases/download/release-master/Regression_test_master_for-SOFA-${{ inputs.sofa_version }}_${RUNNER_OS}.zip
        unzip -qq "${{ runner.temp }}/regression_tmp/${RUNNER_OS}.zip" -d "$WORKSPACE_DIR"
        mv "$WORKSPACE_DIR/Regression_test_master_for-SOFA-${{ inputs.sofa_version }}_${RUNNER_OS}" "$WORKSPACE_DIR/Regression_binaries/"
        chmod +x $WORKSPACE_DIR/Regression_binaries/bin/*
        echo "REGRESSION_BINARY_DIR=$WORKSPACE_DIR/Regression_binaries/" >> $GITHUB_ENV

        if [[ "$RUNNER_OS" == "Windows" ]]; then
          echo "${{ inputs.build_dir }}/lib" >> $GITHUB_PATH
          echo "${{ inputs.build_dir }}/bin" >> $GITHUB_PATH

          pythonroot="$(dirname ${{ inputs.python_exe }})"
          pythonroot="$(cd "$pythonroot" && pwd)"
          echo "$pythonroot" >> $GITHUB_PATH
          echo "$pythonroot/DLLs" >> $GITHUB_PATH
          echo "$pythonroot/Lib" >> $GITHUB_PATH

          echo "${{ inputs.sofa_root }}/plugins/SofaPython3/bin" >> $GITHUB_PATH
          echo "SOFA_PLUGIN_PATH=${{ inputs.build_dir }}/bin" | tee -a $GITHUB_ENV
          
        else
          echo "SOFA_PLUGIN_PATH=${{ inputs.build_dir }}/lib" | tee -a $GITHUB_ENV
        fi

        if [[ "$RUNNER_OS" == "macOS" ]]; then
          echo "DYLD_LIBRARY_PATH=${{ inputs.build_dir }}/lib:${{ inputs.sofa_root }}/lib:${{ inputs.sofa_root }}/plugins/SofaPython3/lib:$DYLD_LIBRARY_PATH" | tee -a $GITHUB_ENV
        fi

        if [[ "$RUNNER_OS" == "Linux" ]]; then
          echo "LD_LIBRARY_PATH=${{ inputs.build_dir }}/lib:${{ inputs.sofa_root }}/lib:${{ inputs.sofa_root }}/plugins/SofaPython3/lib:$LD_LIBRARY_PATH" | tee -a $GITHUB_ENV
        fi

        echo "SOFA_ROOT=${{ inputs.sofa_root }}"  | tee -a $GITHUB_ENV

    - name: Install missing pip packages
      shell: bash
      run: |
        python3 -m pip install prettytable

    - name: Launch unit tests
      if: always() && inputs.run_unit_tests == 'true'
      shell: bash
      run: |
        /bin/bash "$CI_DIR/scripts/unit-tests.sh" run unit "${{ inputs.build_dir }}" "${{ inputs.src_dir }}" "${{ inputs.output_dir }}" ${{ inputs.nb_parallel_threads }}
        /bin/bash "$CI_DIR/scripts/unit-tests.sh" print-summary unit "${{ inputs.build_dir }}" "${{ inputs.src_dir }}" "${{ inputs.output_dir }}" ${{ inputs.nb_parallel_threads }}

        echo "tests_suites=$(/bin/bash "$CI_DIR/scripts/unit-tests.sh" count-test-suites unit ${{ inputs.build_dir }} ${{ inputs.src_dir }} ${{ inputs.output_dir }})" > ${{ inputs.output_dir }}/unit-tests/unit-tests_results.txt
        echo "tests_total=$(/bin/bash "$CI_DIR/scripts/unit-tests.sh" count-tests unit ${{ inputs.build_dir }} ${{ inputs.src_dir }} ${{ inputs.output_dir }})" >> ${{ inputs.output_dir }}/unit-tests/unit-tests_results.txt
        echo "tests_disabled=$(/bin/bash "$CI_DIR/scripts/unit-tests.sh" count-disabled unit ${{ inputs.build_dir }} ${{ inputs.src_dir }} ${{ inputs.output_dir }})" >> ${{ inputs.output_dir }}/unit-tests/unit-tests_results.txt
        echo "tests_failures=$(/bin/bash "$CI_DIR/scripts/unit-tests.sh" count-failures unit ${{ inputs.build_dir }} ${{ inputs.src_dir }} ${{ inputs.output_dir }})" >> ${{ inputs.output_dir }}/unit-tests/unit-tests_results.txt
        echo "tests_errors=$(/bin/bash "$CI_DIR/scripts/unit-tests.sh" count-errors unit ${{ inputs.build_dir }} ${{ inputs.src_dir }} ${{ inputs.output_dir }})" >> ${{ inputs.output_dir }}/unit-tests/unit-tests_results.txt
        echo "tests_duration=$(/bin/bash "$CI_DIR/scripts/unit-tests.sh" count-durations unit ${{ inputs.build_dir }} ${{ inputs.src_dir }} ${{ inputs.output_dir }})" >> ${{ inputs.output_dir }}/unit-tests/unit-tests_results.txt
        
        python3 "$CI_DIR/scripts/exctractErrorFromXML.py" "${{ inputs.output_dir }}/unit-tests/reports" "${{ inputs.output_dir }}/unit-tests"


    - name: Launch scene tests
      if: always() && inputs.run_scene_tests == 'true'
      shell: bash
      run: |
        /bin/bash "$CI_DIR/scripts/scene-tests.sh" run "${{ inputs.sofa_root }}" "${{ inputs.src_dir }}" "${{ inputs.output_dir }}" ${{ inputs.nb_parallel_threads }}
        /bin/bash "$CI_DIR/scripts/scene-tests.sh" print-summary "${{ inputs.sofa_root }}" "${{ inputs.src_dir }}" "${{ inputs.output_dir }}" ${{ inputs.nb_parallel_threads }}

        echo "scenes_total=$(/bin/bash $CI_DIR/scripts/scene-tests.sh count-tested-scenes ${{ inputs.build_dir }} ${{ inputs.src_dir }} ${{ inputs.output_dir }})" > ${{ inputs.output_dir }}/scene-tests/scene-tests_results.txt
        echo "scenes_successes=$(/bin/bash "$CI_DIR/scripts/scene-tests.sh" count-successes ${{ inputs.build_dir }} ${{ inputs.src_dir }} ${{ inputs.output_dir }})" >> ${{ inputs.output_dir }}/scene-tests/scene-tests_results.txt
        echo "scenes_errors=$(/bin/bash "$CI_DIR/scripts/scene-tests.sh" count-errors ${{ inputs.build_dir }} ${{ inputs.src_dir }} ${{ inputs.output_dir }})" >> ${{ inputs.output_dir }}/scene-tests/scene-tests_results.txt
        echo "scenes_crashes=$(/bin/bash "$CI_DIR/scripts/scene-tests.sh" count-crashes ${{ inputs.build_dir }} ${{ inputs.src_dir }} ${{ inputs.output_dir }})" >> ${{ inputs.output_dir }}/scene-tests/scene-tests_results.txt
        echo "scenes_duration=$(/bin/bash "$CI_DIR/scripts/scene-tests.sh" count-durations ${{ inputs.build_dir }} ${{ inputs.src_dir }} ${{ inputs.output_dir }})" >> ${{ inputs.output_dir }}/scene-tests/scene-tests_results.txt


        if [[ -f "${{ inputs.output_dir }}/scene-tests/reports/crashes.txt" && "$(cat "${{ inputs.output_dir }}/scene-tests/reports/crashes.txt")" != "" ]]; then
            cp ${{ inputs.output_dir }}/scene-tests/reports/crashes.txt ${{ inputs.output_dir }}/scene-tests_crashes
        fi
        if [[ -f "${{ inputs.output_dir }}/scene-tests/reports/errors.txt" && "$(cat "${{ inputs.output_dir }}/scene-tests/reports/errors.txt")" != "" ]]; then
            cp ${{ inputs.output_dir }}/scene-tests/reports/errors.txt ${{ inputs.output_dir }}/scene-tests_errors
        fi


    - name: Launch regression tests
      if: always() && inputs.run_regression_tests == 'true'
      shell: bash
      run: |
        /bin/bash "$CI_DIR/scripts/unit-tests.sh" run regression "$REGRESSION_BINARY_DIR" "${{ inputs.src_dir }}" "${{ inputs.output_dir }}" ${{ inputs.nb_parallel_threads }}
        /bin/bash "$CI_DIR/scripts/unit-tests.sh" print-summary regression "$REGRESSION_BINARY_DIR" "${{ inputs.src_dir }}" "${{ inputs.output_dir }}" ${{ inputs.nb_parallel_threads }}

        echo "regressions_suites=$(/bin/bash "$CI_DIR/scripts/unit-tests.sh" count-test-suites regression $REGRESSION_BINARY_DIR ${{ inputs.src_dir }} ${{ inputs.output_dir }} )" > ${{ inputs.output_dir }}/regression-tests/regression-tests_results.txt
        echo "regressions_total=$(/bin/bash "$CI_DIR/scripts/unit-tests.sh" count-tests regression $REGRESSION_BINARY_DIR ${{ inputs.src_dir }} ${{ inputs.output_dir }} )" >> ${{ inputs.output_dir }}/regression-tests/regression-tests_results.txt
        echo "regressions_disabled=$(/bin/bash "$CI_DIR/scripts/unit-tests.sh" count-disabled regression $REGRESSION_BINARY_DIR ${{ inputs.src_dir }} ${{ inputs.output_dir }} )" >> ${{ inputs.output_dir }}/regression-tests/regression-tests_results.txt
        echo "regressions_failures=$(/bin/bash "$CI_DIR/scripts/unit-tests.sh" count-failures regression $REGRESSION_BINARY_DIR ${{ inputs.src_dir }} ${{ inputs.output_dir }} )" >> ${{ inputs.output_dir }}/regression-tests/regression-tests_results.txt
        echo "regressions_errors=$(/bin/bash "$CI_DIR/scripts/unit-tests.sh" count-errors regression $REGRESSION_BINARY_DIR ${{ inputs.src_dir }} ${{ inputs.output_dir }} )" >> ${{ inputs.output_dir }}/regression-tests/regression-tests_results.txt
        echo "regressions_duration=$(/bin/bash "$CI_DIR/scripts/unit-tests.sh" count-durations regression $REGRESSION_BINARY_DIR ${{ inputs.src_dir }} ${{ inputs.output_dir }} )" >> ${{ inputs.output_dir }}/regression-tests/regression-tests_results.txt
 
        "$CI_DIR/scripts/exctractErrorFromXML.py" "${{ inputs.output_dir }}/regression-tests/reports" "${{ inputs.output_dir }}/regression-tests"


    - name: Summarize tests results
      shell: bash
      run: |
        if [[ "$(cd "${{ inputs.output_dir }}" && find . -maxdepth 1 -type f)" != "" ]]; then
          echo "❌ Tests have resulted in : "
          echo ""
          python3 $CI_DIR/scripts/generate-tests-table.py "${{ inputs.output_dir }}"
          echo ""
          echo "#----------------------------------------#"
          echo "#---------------Quick Logs---------------#"
          echo "#----------------------------------------#"
          for testType in 'unit' 'scene' 'regression';
            do 
              for errorType in 'errors' 'crashes' 'failures';
              do
                if [ -f "${{ inputs.output_dir }}/${testType}-tests_${errorType}" ]; then 
                  capitalized="$(echo "${testType:0:1}" | tr '[:lower:]' '[:upper:]')${testType:1}"
                  echo ""
                  echo -e "${bold}${capitalized} ${errorType}:${normal}"
                  echo ""
                  cat "${{ inputs.output_dir }}/${testType}-tests_${errorType}"
                  echo ""
                  echo "#----------------------------------------#"
                fi
              done
            done
          echo -e "${bold}You can download all logs here : ${{ steps.publish-tests-logs.outputs.artifact-url }}${normal}"
          exit 1
        elif [[ "${{ steps.unit-tests-step.outcome }}" == "failure" || "${{ steps.scene-tests-step.outcome }}" == "failure" || "${{ steps.regression-tests-step.outcome }}" == "failure" ]]; then
          echo "❌ Something whent wrong during one of the tests steps"
          echo -e "${bold}Please check this action logs, and download tests logs here: ${{ steps.publish-tests-logs.outputs.artifact-url }}${normal}"
          exit 1
        else
          echo "✅ Tests where successful : "
          echo ""
          python3 $CI_DIR/scripts/generate-tests-table.py "${{ inputs.output_dir }}/"
          echo ""
        fi

    - name: Publish tests logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: tests-logs-${{ runner.os }}
        path: |
            ${{ inputs.output_dir }}
