# Action description and parameters
name: 'SOFA Setup Action'
description: 'Setup everything needed to build a SOFA plugin'
inputs:
  sofa_install_path:
    description: 'Sofa install directory'
    required: true
  local_artifact_path :
    description: 'path to the install directory of the current plugin'
    required: false
  sofa_version:
    description: 'Sofa installed version'
    required: true
  regression_file_path:
    description: 'Regression test configuration file directory'
    required: true
outputs:
  regression_test_results:
    description: "Log file containing regression tests results"
    value: ${{ steps.set-env-vars.outputs.regression_test_results_path }}

# Action code
runs:
  using: "composite"
  steps:
    - name: Setup env
      shell: bash
      run: |
        # Set executable extension
        EXE=''      
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          EXE='.exe'
        fi
        echo "EXE=$EXE" | tee -a $GITHUB_ENV
        
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          if [[ -z "${{ inputs.local_artifact_path }}" ]]; then
            echo "${{ inputs.local_artifact_path }}/lib" >> $GITHUB_PATH
            echo "${{ inputs.local_artifact_path }}/bin" >> $GITHUB_PATH
            echo "SOFA_PLUGIN_PATH=${{ inputs.local_artifact_path }}/bin" | tee -a $GITHUB_ENV
          fi
          echo "$SOFA_ROOT/plugins/SofaPython3/bin" >> $GITHUB_PATH
        else
          if [[ -z "${{ inputs.local_artifact_path }}" ]]; then
            echo "SOFA_PLUGIN_PATH=${{ inputs.local_artifact_path }}/lib" | tee -a $GITHUB_ENV
          fi
        fi
        
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          if [[ ! -z "${{ inputs.local_artifact_path }}" ]]; then
           LOCAL_ARTIFACT=${{ inputs.local_artifact_path }}/lib
          fi
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${{ inputs.sofa_install_path }}/lib:$SOFA_ROOT/plugins/SofaPython3/lib:$LOCAL_ARTIFACT" | tee -a $GITHUB_ENV
        fi
        echo "SOFAPYTHON3_PLUGINS_PATH=${{ inputs.sofa_install_path }}/plugins/SofaPython3/lib/python3/site-packages" | tee -a $GITHUB_ENV

    - name: Fetch and install Regression_test
      shell: bash
      run: |
        if [[ "$RUNNER_OS" != "macOS" ]]; then
          # Get regression from github releases
          mkdir -p "${{ runner.temp }}/regression_tmp/install"
          curl --output "${{ runner.temp }}/regression_tmp/${RUNNER_OS}.zip" -L https://github.com/sofa-framework/regression/releases/download/release-master/Regression_test_master_for-SOFA-${{ inputs.sofa_version }}_$RUNNER_OS.zip
          unzip -qq "${{ runner.temp }}/regression_tmp/${RUNNER_OS}.zip" -d "${{ runner.temp }}/regression_tmp/install"
          # Install it in the SOFA bin directory
          $SUDO mv "${{ runner.temp }}"/regression_tmp/install/Regression_*/bin/* "${SOFA_ROOT}/bin"
          chmod +x ${SOFA_ROOT}/bin/Regression_test${{ env.EXE }}
          export REGRESSION_SCENES_DIR="${{ inputs.regression_file_path }}"
          # Run regression test bench
          ${SOFA_ROOT}/bin/Regression_test${{ env.EXE }}
        else
          echo "Regression tests are not supported on the CI for macOS yet (TODO)"
        fi

    - name: Run regression tests
      shell: bash
      run: |