name: Test sofa-setup-action

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  run:
    name: Run on ${{ matrix.os }} with SOFA ${{ matrix.sofa_branch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-test]
        sofa_branch: [master]

    steps:
#      - name: Setup SOFA and environment
#        id: sofa
#        uses: sofa-framework/sofa-setup-action@v4
#        with:
#          sofa_root: ${{ github.workspace }}/sofa
#          sofa_version: ${{ matrix.sofa_branch }}
#          sofa_scope: 'full'

      - name: Launch test
        id: tests
        uses: bakpaul/sofa-test-action@only_add_regression
        with:
          sofa_install_path: ${{ github.workspace }}/sofa
          regression_file_path: ${{ github.workspace }}/sofa/example
          regression_reference_path: ${{ github.workspace }}/sofa/applications/projects/Regression/references/examples
          sofa_version: ${{ matrix.sofa_branch }}


